include = ["*.py"]
indent-width = 4
line-length = 88

[lint]
select = ["E4", "E7", "E9", "F", "Q", "ERA", "T", "B"]
extend-select = ["C90", "UP"]
ignore = ["B006", "UP006", "UP035"]

[lint.per-file-ignores]
"*/routes.py" = ["B008"]
"*/service*.py" = ["UP034", "B008"]


[lint.isort]
order-by-type = true

[lint.pylint]
max-branches = 10
max-locals = 20